import { AppBlock, events } from "@slflows/sdk/v1";
import { computeFetch } from "../../lib/restClient.ts";

const insert: AppBlock = {
  name: "Storage Pools - Insert",
  description: `Creates a wire group in the specified project in the given scope using the parameters that are included in the request.`,
  category: "Storage Pools",
  inputs: {
    default: {
      config: {
        zone: {
          name: "Zone",
          description:
            "Output only. [Output Only] URL of the zone where the storage pool resides. You must specify this field as part of the HTTP request URL. It is not settable as a field in the request body.",
          type: {
            type: "string",
            description:
              "Output only. [Output Only] URL of the zone where the storage pool resides. You must specify this field as part of the HTTP request URL. It is not settable as a field in the request body.",
          },
          required: false,
        },
        capacity_provisioning_type: {
          name: "Capacity Provisioning Type",
          description:
            "Provisioning type of the byte capacity of the pool. Check the CapacityProvisioningType enum for the list of possible values.",
          type: {
            type: "string",
            description:
              "Provisioning type of the byte capacity of the pool. Check the CapacityProvisioningType enum for the list of possible values.",
          },
          required: false,
        },
        creation_timestamp: {
          name: "Creation Timestamp",
          description:
            "Output only. [Output Only] Creation timestamp inRFC3339 text format.",
          type: {
            type: "string",
            description:
              "Output only. [Output Only] Creation timestamp inRFC3339 text format.",
          },
          required: false,
        },
        description: {
          name: "Description",
          description:
            "An optional description of this resource. Provide this property when you create the resource.",
          type: {
            type: "string",
            description:
              "An optional description of this resource. Provide this property when you create the resource.",
          },
          required: false,
        },
        exapool_provisioned_capacity_gb: {
          name: "Exapool Provisioned Capacity Gb",
          description:
            "Output only. [Output Only] Provisioned capacities for each SKU for this Exapool in GiB",
          type: {
            type: "object",
            properties: {
              capacity_optimized: {
                type: "string",
                description: "64-bit integer as string",
              },
              read_optimized: {
                type: "string",
                description: "64-bit integer as string",
              },
              write_optimized: {
                type: "string",
                description: "64-bit integer as string",
              },
            },
            description: "Exapool provisioned capacities for each SKU type",
            additionalProperties: true,
          },
          required: false,
        },
        id: {
          name: "Id",
          description:
            "Output only. [Output Only] The unique identifier for the resource. This identifier is defined by the server.",
          type: {
            type: "string",
            description: "64-bit integer as string",
          },
          required: false,
        },
        kind: {
          name: "Kind",
          description:
            "Output only. [Output Only] Type of the resource. Always compute#storagePool for storage pools.",
          type: {
            type: "string",
            description:
              "Output only. [Output Only] Type of the resource. Always compute#storagePool for storage pools.",
          },
          required: false,
        },
        label_fingerprint: {
          name: "Label Fingerprint",
          description:
            "A fingerprint for the labels being applied to this storage pool, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error412 conditionNotMet.  To see the latest fingerprint, make a get() request to retrieve a storage pool.",
          type: {
            type: "string",
            description:
              "A fingerprint for the labels being applied to this storage pool, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error412 conditionNotMet.  To see the latest fingerprint, make a get() request to retrieve a storage pool.",
          },
          required: false,
        },
        labels: {
          name: "Labels",
          description:
            "Labels to apply to this storage pool. These can be later modified by the setLabels method.",
          type: {
            type: "object",
            additionalProperties: {
              type: "string",
            },
            description:
              "Labels to apply to this storage pool. These can be later modified by the setLabels method.",
          },
          required: false,
        },
        name: {
          name: "Name",
          description:
            "Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and comply withRFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.",
          type: {
            type: "string",
            description:
              "Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and comply withRFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.",
          },
          required: false,
        },
        params: {
          name: "Params",
          description:
            "Input only. Additional params passed with the request, but not persisted as part of resource payload.",
          type: {
            type: "object",
            properties: {
              resource_manager_tags: {
                type: "object",
                additionalProperties: {
                  type: "string",
                },
                description:
                  "Input only. Resource manager tags to be bound to the storage pool. Tag keys and values have the same definition as resource manager tags. Keys and values can be either in numeric format, such as `tagKeys/{tag_key_id}` and `tagValues/456` or in namespaced format such as `{org_id|project_id}/{tag_key_short_name}` and `{tag_value_short_name}`. The field is ignored (both PUT & PATCH) when empty.",
              },
            },
            description: "Additional storage pool params.",
            additionalProperties: true,
          },
          required: false,
        },
        performance_provisioning_type: {
          name: "Performance Provisioning Type",
          description:
            "Provisioning type of the performance-related parameters of the pool, such as throughput and IOPS. Check the PerformanceProvisioningType enum for the list of possible values.",
          type: {
            type: "string",
            description:
              "Provisioning type of the performance-related parameters of the pool, such as throughput and IOPS. Check the PerformanceProvisioningType enum for the list of possible values.",
          },
          required: false,
        },
        pool_provisioned_capacity_gb: {
          name: "Pool Provisioned Capacity Gb",
          description:
            "Size of the storage pool in GiB. For more information about the size limits, see https://cloud.google.com/compute/docs/disks/storage-pools.",
          type: {
            type: "string",
            description: "64-bit integer as string",
          },
          required: false,
        },
        pool_provisioned_iops: {
          name: "Pool Provisioned Iops",
          description:
            "Provisioned IOPS of the storage pool. Only relevant if the storage pool type is hyperdisk-balanced.",
          type: {
            type: "string",
            description: "64-bit integer as string",
          },
          required: false,
        },
        pool_provisioned_throughput: {
          name: "Pool Provisioned Throughput",
          description:
            "Provisioned throughput of the storage pool in MiB/s. Only relevant if the storage pool type is hyperdisk-balanced or hyperdisk-throughput.",
          type: {
            type: "string",
            description: "64-bit integer as string",
          },
          required: false,
        },
        resource_status: {
          name: "Resource Status",
          description:
            "Output only. [Output Only] Status information for the storage pool resource.",
          type: {
            type: "object",
            properties: {
              disk_count: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_read_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_read_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_write_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_write_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
              last_resize_timestamp: {
                type: "string",
                description:
                  "Output only. [Output Only] Timestamp of the last successful resize inRFC3339 text format.",
              },
              max_total_provisioned_disk_capacity_gb: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_used_capacity_bytes: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_used_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_used_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_user_written_bytes: {
                type: "string",
                description: "64-bit integer as string",
              },
              total_provisioned_disk_capacity_gb: {
                type: "string",
                description: "64-bit integer as string",
              },
              total_provisioned_disk_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              total_provisioned_disk_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
            },
            description: "[Output Only] Contains output only fields.",
            additionalProperties: true,
          },
          required: false,
        },
        self_link: {
          name: "Self Link",
          description:
            "Output only. [Output Only] Server-defined fully-qualified URL for this resource.",
          type: {
            type: "string",
            description:
              "Output only. [Output Only] Server-defined fully-qualified URL for this resource.",
          },
          required: false,
        },
        self_link_with_id: {
          name: "Self Link With Id",
          description:
            "Output only. [Output Only] Server-defined URL for this resource's resource id.",
          type: {
            type: "string",
            description:
              "Output only. [Output Only] Server-defined URL for this resource's resource id.",
          },
          required: false,
        },
        state: {
          name: "State",
          description:
            "Output only. [Output Only] The status of storage pool creation.        - CREATING: Storage pool is provisioning.      storagePool.      - FAILED: Storage pool creation failed.      - READY: Storage pool is ready for use.      - DELETING: Storage pool is deleting. Check the State enum for the list of possible values.",
          type: {
            type: "string",
            description:
              "Output only. [Output Only] The status of storage pool creation.        - CREATING: Storage pool is provisioning.      storagePool.      - FAILED: Storage pool creation failed.      - READY: Storage pool is ready for use.      - DELETING: Storage pool is deleting. Check the State enum for the list of possible values.",
          },
          required: false,
        },
        status: {
          name: "Status",
          description:
            "Output only. [Output Only] Status information for the storage pool resource.",
          type: {
            type: "object",
            properties: {
              disk_count: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_read_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_read_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_write_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              exapool_max_write_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
              last_resize_timestamp: {
                type: "string",
                description:
                  "Output only. [Output Only] Timestamp of the last successful resize inRFC3339 text format.",
              },
              max_total_provisioned_disk_capacity_gb: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_used_capacity_bytes: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_used_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_used_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
              pool_user_written_bytes: {
                type: "string",
                description: "64-bit integer as string",
              },
              total_provisioned_disk_capacity_gb: {
                type: "string",
                description: "64-bit integer as string",
              },
              total_provisioned_disk_iops: {
                type: "string",
                description: "64-bit integer as string",
              },
              total_provisioned_disk_throughput: {
                type: "string",
                description: "64-bit integer as string",
              },
            },
            description: "[Output Only] Contains output only fields.",
            additionalProperties: true,
          },
          required: false,
        },
        storage_pool_type: {
          name: "Storage Pool Type",
          description: "Type of the storage pool.",
          type: {
            type: "string",
            description: "Type of the storage pool.",
          },
          required: false,
        },
        request_id: {
          name: "Request Id",
          description:
            "An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed.  For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments.  The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000).",
          type: {
            type: "string",
          },
          required: false,
        },
      },
      onEvent: async (input) => {
        const pathParams: Record<string, string> = {};
        pathParams.project = input.app.config.projectId as string;
        if (input.event.inputConfig.zone !== undefined)
          pathParams["zone"] = String(input.event.inputConfig.zone);

        const queryParams: Record<string, string> = {};
        if (input.event.inputConfig.request_id !== undefined)
          queryParams["requestId"] = String(input.event.inputConfig.request_id);
        const body: Record<string, any> = {};
        if (input.event.inputConfig.capacity_provisioning_type !== undefined)
          body.capacity_provisioning_type =
            input.event.inputConfig.capacity_provisioning_type;
        if (input.event.inputConfig.creation_timestamp !== undefined)
          body.creation_timestamp = input.event.inputConfig.creation_timestamp;
        if (input.event.inputConfig.description !== undefined)
          body.description = input.event.inputConfig.description;
        if (
          input.event.inputConfig.exapool_provisioned_capacity_gb !== undefined
        )
          body.exapool_provisioned_capacity_gb =
            input.event.inputConfig.exapool_provisioned_capacity_gb;
        if (input.event.inputConfig.id !== undefined)
          body.id = input.event.inputConfig.id;
        if (input.event.inputConfig.kind !== undefined)
          body.kind = input.event.inputConfig.kind;
        if (input.event.inputConfig.label_fingerprint !== undefined)
          body.label_fingerprint = input.event.inputConfig.label_fingerprint;
        if (input.event.inputConfig.labels !== undefined)
          body.labels = input.event.inputConfig.labels;
        if (input.event.inputConfig.name !== undefined)
          body.name = input.event.inputConfig.name;
        if (input.event.inputConfig.params !== undefined)
          body.params = input.event.inputConfig.params;
        if (input.event.inputConfig.performance_provisioning_type !== undefined)
          body.performance_provisioning_type =
            input.event.inputConfig.performance_provisioning_type;
        if (input.event.inputConfig.pool_provisioned_capacity_gb !== undefined)
          body.pool_provisioned_capacity_gb =
            input.event.inputConfig.pool_provisioned_capacity_gb;
        if (input.event.inputConfig.pool_provisioned_iops !== undefined)
          body.pool_provisioned_iops =
            input.event.inputConfig.pool_provisioned_iops;
        if (input.event.inputConfig.pool_provisioned_throughput !== undefined)
          body.pool_provisioned_throughput =
            input.event.inputConfig.pool_provisioned_throughput;
        if (input.event.inputConfig.resource_status !== undefined)
          body.resource_status = input.event.inputConfig.resource_status;
        if (input.event.inputConfig.self_link !== undefined)
          body.self_link = input.event.inputConfig.self_link;
        if (input.event.inputConfig.self_link_with_id !== undefined)
          body.self_link_with_id = input.event.inputConfig.self_link_with_id;
        if (input.event.inputConfig.state !== undefined)
          body.state = input.event.inputConfig.state;
        if (input.event.inputConfig.status !== undefined)
          body.status = input.event.inputConfig.status;
        if (input.event.inputConfig.storage_pool_type !== undefined)
          body.storage_pool_type = input.event.inputConfig.storage_pool_type;
        if (input.event.inputConfig.zone !== undefined)
          body.zone = input.event.inputConfig.zone;

        const result = await computeFetch({
          config: input.app.config,
          method: "POST",
          pathTemplate:
            "/compute/v1/projects/{project}/zones/{zone}/storagePools",
          pathParams,
          queryParams,
          body: Object.keys(body).length > 0 ? body : undefined,
        });

        await events.emit(result || {});
      },
    },
  },
  outputs: {
    default: {
      possiblePrimaryParents: ["default"],
      type: {
        type: "object",
        properties: {
          client_operation_id: {
            type: "string",
            description:
              "[Output Only] The value of `requestId` if you provided it in the request. Not present otherwise.",
          },
          creation_timestamp: {
            type: "string",
            description: "[Deprecated] This field is deprecated.",
          },
          description: {
            type: "string",
            description:
              "[Output Only] A textual description of the operation, which is set when the operation is created.",
          },
          end_time: {
            type: "string",
            description:
              "[Output Only] The time that this operation was completed. This value is inRFC3339 text format.",
          },
          error: {
            type: "object",
            properties: {
              errors: {
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    code: {
                      type: "string",
                      description:
                        "[Output Only] The error type identifier for this error.",
                    },
                    error_details: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          error_info: {
                            type: "object",
                            properties: {
                              domain: {
                                type: "string",
                                description:
                                  'The logical grouping to which the "reason" belongs. The error domain is typically the registered service name of the tool or product that generates the error. Example: "pubsub.googleapis.com". If the error is generated by some common infrastructure, the error domain must be a globally unique value that identifies the infrastructure. For Google API infrastructure, the error domain is "googleapis.com".',
                              },
                              metadatas: {
                                type: "object",
                                additionalProperties: {
                                  type: "string",
                                },
                                description:
                                  'Additional structured details about this error.  Keys must match a regular expression of `a-z+` but should ideally be lowerCamelCase. Also, they must be limited to 64 characters in length. When identifying the current value of an exceeded limit, the units should be contained in the key, not the value.  For example, rather than `{"instanceLimit": "100/request"}`, should be returned as, `{"instanceLimitPerRequest": "100"}`, if the client exceeds the number of instances that can be created in a single (batch) request.',
                              },
                              reason: {
                                type: "string",
                                description:
                                  "The reason of the error. This is a constant value that identifies the proximate cause of the error. Error reasons are unique within a particular domain of errors. This should be at most 63 characters and match a regular expression of `A-Z+[A-Z0-9]`, which represents UPPER_SNAKE_CASE.",
                              },
                            },
                            description:
                              'Describes the cause of the error with structured details.  Example of an error when contacting the "pubsub.googleapis.com" API when it is not enabled:      { "reason": "API_DISABLED"       "domain": "googleapis.com"       "metadata": {         "resource": "projects/123",         "service": "pubsub.googleapis.com"       }     }  This response indicates that the pubsub.googleapis.com API is not enabled.  Example of an error that is returned when attempting to create a Spanner instance in a region that is out of stock:      { "reason": "STOCKOUT"       "domain": "spanner.googleapis.com",       "metadata": {         "availableRegions": "us-central1,us-east2"       }     }',
                            additionalProperties: true,
                          },
                          help: {
                            type: "object",
                            properties: {
                              links: {
                                type: "array",
                                items: {
                                  type: "object",
                                  properties: {
                                    description: {
                                      type: "string",
                                      description:
                                        "Describes what the link offers.",
                                    },
                                    url: {
                                      type: "string",
                                      description: "The URL of the link.",
                                    },
                                  },
                                  description: "Describes a URL link.",
                                  additionalProperties: true,
                                },
                                description:
                                  "URL(s) pointing to additional information on handling the current error.",
                              },
                            },
                            description:
                              "Provides links to documentation or for performing an out of band action.  For example, if a quota check failed with an error indicating the calling project hasn't enabled the accessed service, this can contain a URL pointing directly to the right place in the developer console to flip the bit.",
                            additionalProperties: true,
                          },
                          localized_message: {
                            type: "object",
                            properties: {
                              locale: {
                                type: "string",
                                description:
                                  'The locale used following the specification defined at https://www.rfc-editor.org/rfc/bcp/bcp47.txt. Examples are: "en-US", "fr-CH", "es-MX"',
                              },
                              message: {
                                type: "string",
                                description:
                                  "The localized error message in the above locale.",
                              },
                            },
                            description:
                              "Provides a localized error message that is safe to return to the user which can be attached to an RPC error.",
                            additionalProperties: true,
                          },
                          quota_info: {
                            type: "object",
                            properties: {
                              dimensions: {
                                type: "object",
                                additionalProperties: {
                                  type: "string",
                                },
                                description:
                                  "The map holding related quota dimensions.",
                              },
                              future_limit: {
                                type: "number",
                                description:
                                  "Future quota limit being rolled out. The limit's unit depends on the quota  type or metric.",
                              },
                              limit: {
                                type: "number",
                                description:
                                  "Current effective quota limit. The limit's unit depends on the quota type or metric.",
                              },
                              limit_name: {
                                type: "string",
                                description: "The name of the quota limit.",
                              },
                              metric_name: {
                                type: "string",
                                description:
                                  "The Compute Engine quota metric name.",
                              },
                              rollout_status: {
                                type: "string",
                                description:
                                  "Rollout status of the future quota limit. Check the RolloutStatus enum for the list of possible values.",
                              },
                            },
                            description:
                              "Additional details for quota exceeded error for resource quota.",
                            additionalProperties: true,
                          },
                        },
                        additionalProperties: true,
                      },
                      description:
                        "[Output Only] An optional list of messages that contain the error details. There is a set of defined message types to use for providing details.The syntax depends on the error code. For example, QuotaExceededInfo will have details when the error code is QUOTA_EXCEEDED.",
                    },
                    location: {
                      type: "string",
                      description:
                        "[Output Only] Indicates the field in the request that caused the error. This property is optional.",
                    },
                    message: {
                      type: "string",
                      description:
                        "[Output Only] An optional, human-readable error message.",
                    },
                  },
                  additionalProperties: true,
                },
                description:
                  "[Output Only] The array of errors encountered while processing this operation.",
              },
            },
            description:
              "Output only. Errors that prevented the ResizeRequest to be fulfilled.",
            additionalProperties: true,
          },
          http_error_message: {
            type: "string",
            description:
              "[Output Only] If the operation fails, this field contains the HTTP error message that was returned, such as `NOT FOUND`.",
          },
          http_error_status_code: {
            type: "integer",
            description:
              "[Output Only] If the operation fails, this field contains the HTTP error status code that was returned. For example, a `404` means the resource was not found.",
          },
          id: {
            type: "string",
            description: "64-bit integer as string",
          },
          insert_time: {
            type: "string",
            description:
              "[Output Only] The time that this operation was requested. This value is inRFC3339 text format.",
          },
          instances_bulk_insert_operation_metadata: {
            type: "object",
            properties: {
              per_location_status: {
                type: "object",
                additionalProperties: {
                  type: "string",
                },
                description:
                  "Status information per location (location name is key). Example key: zones/us-central1-a",
              },
            },
            additionalProperties: true,
          },
          kind: {
            type: "string",
            description:
              "Output only. [Output Only] Type of the resource. Always `compute#operation` for Operation resources.",
          },
          name: {
            type: "string",
            description: "[Output Only] Name of the operation.",
          },
          operation_group_id: {
            type: "string",
            description:
              "Output only. [Output Only] An ID that represents a group of operations, such as when a group of operations results from a `bulkInsert` API request.",
          },
          operation_type: {
            type: "string",
            description:
              "[Output Only] The type of operation, such as `insert`, `update`, or `delete`, and so on.",
          },
          progress: {
            type: "integer",
            description:
              "[Output Only] An optional progress indicator that ranges from 0 to 100. There is no requirement that this be linear or support any granularity of operations. This should not be used to guess when the operation will be complete. This number should monotonically increase as the operation progresses.",
          },
          region: {
            type: "string",
            description:
              "[Output Only] The URL of the region where the operation resides. Only applicable when performing regional operations.",
          },
          self_link: {
            type: "string",
            description: "[Output Only] Server-defined URL for the resource.",
          },
          set_common_instance_metadata_operation_metadata: {
            type: "object",
            properties: {
              client_operation_id: {
                type: "string",
                description: "[Output Only] The client operation id.",
              },
              per_location_operations: {
                type: "object",
                additionalProperties: {
                  type: "string",
                },
                description:
                  "[Output Only] Status information per location (location name is key). Example key: zones/us-central1-a",
              },
            },
            additionalProperties: true,
            description:
              "Output only. [Output Only] If the operation is for projects.setCommonInstanceMetadata, this field will contain information on all underlying zonal actions and their state.",
          },
          start_time: {
            type: "string",
            description:
              "[Output Only] The time that this operation was started by the server. This value is inRFC3339 text format.",
          },
          status: {
            type: "string",
            enum: ["UNDEFINED_STATUS", "DONE", "PENDING", "RUNNING"],
            description:
              "The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details.  You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).",
          },
          status_message: {
            type: "string",
            description:
              "[Output Only] An optional textual description of the current status of the operation.",
          },
          target_id: {
            type: "string",
            description: "64-bit integer as string",
          },
          target_link: {
            type: "string",
            description:
              "[Output Only] The URL of the resource that the operation modifies. For operations related to creating a snapshot, this points to the disk that the snapshot was created from.",
          },
          user: {
            type: "string",
            description:
              "[Output Only] User who requested the operation, for example: `user@example.com` or `alice_smith_identifier (global/workforcePools/example-com-us-employees)`.",
          },
          warnings: {
            type: "array",
            items: {
              type: "object",
              properties: {
                code: {
                  type: "string",
                  description:
                    "[Output Only] A warning code, if applicable. For example, Compute Engine returns NO_RESULTS_ON_PAGE if there are no results in the response. Check the Code enum for the list of possible values.",
                },
                data: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      key: {
                        type: "string",
                        description:
                          "[Output Only] A key that provides more detail on the warning being returned. For example, for warnings where there are no results in a list request for a particular zone, this key might be scope and the key value might be the zone name. Other examples might be a key indicating a deprecated resource and a suggested replacement, or a warning about invalid network settings (for example, if an instance attempts to perform IP forwarding but is not enabled for IP forwarding).",
                      },
                      value: {
                        type: "string",
                        description:
                          "[Output Only] A warning data value corresponding to the key.",
                      },
                    },
                    additionalProperties: true,
                  },
                  description:
                    '[Output Only] Metadata about this warning in key: value format. For example:  "data": [   {    "key": "scope",    "value": "zones/us-east1-d"   }',
                },
                message: {
                  type: "string",
                  description:
                    "[Output Only] A human-readable description of the warning code.",
                },
              },
              additionalProperties: true,
            },
            description:
              "[Output Only] If warning messages are generated during processing of the operation, this field will be populated.",
          },
          zone: {
            type: "string",
            description:
              "[Output Only] The URL of the zone where the operation resides. Only applicable when performing per-zone operations.",
          },
        },
        description:
          "Represents an Operation resource.  Google Compute Engine has three Operation resources:  * [Global](/compute/docs/reference/rest/v1/globalOperations) * [Regional](/compute/docs/reference/rest/v1/regionOperations) * [Zonal](/compute/docs/reference/rest/v1/zoneOperations)  You can use an operation resource to manage asynchronous API requests. For more information, readHandling API responses.  Operations can be global, regional or zonal.     - For global operations, use the `globalOperations`    resource.    - For regional operations, use the    `regionOperations` resource.    - For zonal operations, use    the `zoneOperations` resource.    For more information, read Global, Regional, and Zonal Resources.  Note that completed Operation resources have a limited retention period.",
        additionalProperties: true,
      },
    },
  },
};

export default insert;
