import { AppBlock, events } from "@slflows/sdk/v1";
import { computeFetch } from "../../lib/restClient.ts";

const get: AppBlock = {
  name: "Addresses - Get",
  description: `Returns the specified Zone resource.`,
  category: "Addresses",
  inputs: {
    default: {
      config: {
        region: {
          name: "Region",
          description: "Name of the region for this request.",
          type: {
            type: "string",
          },
          required: true,
        },
        address: {
          name: "Address",
          description: "Name of the address resource to return.",
          type: {
            type: "string",
          },
          required: true,
        },
      },
      onEvent: async (input) => {
        const pathParams: Record<string, string> = {};
        pathParams.project = input.app.config.projectId as string;
        if (input.event.inputConfig.region !== undefined)
          pathParams["region"] = String(input.event.inputConfig.region);
        if (input.event.inputConfig.address !== undefined)
          pathParams["address"] = String(input.event.inputConfig.address);

        const result = await computeFetch({
          config: input.app.config,
          method: "GET",
          pathTemplate:
            "/compute/v1/projects/{project}/regions/{region}/addresses/{address}",
          pathParams,
        });

        await events.emit(result || {});
      },
    },
  },
  outputs: {
    default: {
      possiblePrimaryParents: ["default"],
      type: {
        type: "object",
        properties: {
          address: {
            type: "string",
            description: "The static IP address represented by this resource.",
          },
          address_type: {
            type: "string",
            description:
              "The type of address to reserve, either INTERNAL orEXTERNAL. If unspecified, defaults to EXTERNAL. Check the AddressType enum for the list of possible values.",
          },
          creation_timestamp: {
            type: "string",
            description:
              "Output only. [Output Only] Creation timestamp inRFC3339 text format.",
          },
          description: {
            type: "string",
            description:
              "An optional description of this resource. Provide this field when you create the resource.",
          },
          id: {
            type: "string",
            description: "64-bit integer as string",
          },
          ip_collection: {
            type: "string",
            description:
              "Reference to the source of external IPv4 addresses, like a PublicDelegatedPrefix (PDP) for BYOIP. The PDP must support enhanced IPv4 allocations.  Use one of the following formats to specify a PDP when reserving an external IPv4 address using BYOIP.     -    Full resource URL, as inhttps://www.googleapis.com/compute/v1/projects/projectId/regions/region/publicDelegatedPrefixes/pdp-name    -    Partial URL, as in             - projects/projectId/regions/region/publicDelegatedPrefixes/pdp-name           - regions/region/publicDelegatedPrefixes/pdp-name",
          },
          ip_version: {
            type: "string",
            description:
              "The IP version that will be used by this address. Valid options areIPV4 or IPV6. Check the IpVersion enum for the list of possible values.",
          },
          ipv6_endpoint_type: {
            type: "string",
            description:
              "The endpoint type of this address, which should be VM or NETLB. This is used for deciding which type of endpoint this address can be used after the external IPv6 address reservation. Check the Ipv6EndpointType enum for the list of possible values.",
          },
          kind: {
            type: "string",
            description:
              "Output only. [Output Only] Type of the resource. Always compute#address for addresses.",
          },
          label_fingerprint: {
            type: "string",
            description:
              "A fingerprint for the labels being applied to this Address, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels, otherwise the request will fail with error412 conditionNotMet.  To see the latest fingerprint, make a get() request to retrieve an Address.",
          },
          labels: {
            type: "object",
            additionalProperties: {
              type: "string",
            },
            description:
              "Labels for this resource. These can only be added or modified by thesetLabels method. Each label key/value pair must comply withRFC1035. Label values may be empty.",
          },
          name: {
            type: "string",
            description:
              "Name of the resource. Provided by the client when the resource is created. The name must be 1-63 characters long, and comply withRFC1035. Specifically, the name must be 1-63 characters long and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?`. The first character must be a lowercase letter, and all following characters (except for the last character) must be a dash, lowercase letter, or digit. The last character must be a lowercase letter or digit.",
          },
          network: {
            type: "string",
            description:
              "The URL of the network in which to reserve the address. This field can only be used with INTERNAL type with theVPC_PEERING purpose.",
          },
          network_tier: {
            type: "string",
            description:
              "This signifies the networking tier used for configuring this address and can only take the following values: PREMIUM orSTANDARD. Internal IP addresses are always Premium Tier; global external IP addresses are always Premium Tier; regional external IP addresses can be either Standard or Premium Tier.  If this field is not specified, it is assumed to be PREMIUM. Check the NetworkTier enum for the list of possible values.",
          },
          prefix_length: {
            type: "integer",
            description:
              "The prefix length if the resource represents an IP range.",
          },
          purpose: {
            type: "string",
            description:
              "The purpose of this resource, which can be one of the following values:        - GCE_ENDPOINT for addresses that are used by VM      instances, alias IP ranges, load balancers, and similar resources.      - DNS_RESOLVER for a DNS resolver address in a subnetwork        for a Cloud DNS  inbound        forwarder IP addresses (regional internal IP address in a subnet of        a VPC network)      - VPC_PEERING for global internal IP addresses used for            private services access allocated ranges.      - NAT_AUTO for the regional external IP addresses used by           Cloud NAT when allocating addresses using            automatic NAT IP address allocation.      - IPSEC_INTERCONNECT for addresses created from a private      IP range that are reserved for a VLAN attachment in an      *HA VPN over Cloud Interconnect* configuration. These addresses      are regional resources.      - `SHARED_LOADBALANCER_VIP` for an internal IP address that is assigned      to multiple internal forwarding rules.      - `PRIVATE_SERVICE_CONNECT` for a private network address that is      used to configure Private Service Connect. Only global internal addresses      can use this purpose. Check the Purpose enum for the list of possible values.",
          },
          region: {
            type: "string",
            description:
              "Output only. [Output Only] The URL of the region where a regional address resides. For regional addresses, you must specify the region as a path parameter in the HTTP request URL. *This field is not applicable to global addresses.*",
          },
          self_link: {
            type: "string",
            description: "[Output Only] Server-defined URL for the resource.",
          },
          status: {
            type: "string",
            description:
              "Output only. [Output Only] The status of the address, which can be one ofRESERVING, RESERVED, or IN_USE. An address that is RESERVING is currently in the process of being reserved. A RESERVED address is currently reserved and available to use. An IN_USE address is currently being used by another resource and is not available. Check the Status enum for the list of possible values.",
          },
          subnetwork: {
            type: "string",
            description:
              "The URL of the subnetwork in which to reserve the address. If an IP address is specified, it must be within the subnetwork's IP range. This field can only be used with INTERNAL type with aGCE_ENDPOINT or DNS_RESOLVER purpose.",
          },
          users: {
            type: "array",
            items: {
              type: "string",
            },
            description:
              "[Output Only] The URLs of the resources that are using this address.",
          },
        },
        description:
          "Represents an IP Address resource.  Google Compute Engine has two IP Address resources:  * [Global (external and internal)](https://cloud.google.com/compute/docs/reference/rest/v1/globalAddresses) * [Regional (external and internal)](https://cloud.google.com/compute/docs/reference/rest/v1/addresses)  For more information, see Reserving a static external IP address.",
        additionalProperties: true,
      },
    },
  },
};

export default get;
