import { AppBlock, events } from "@slflows/sdk/v1";
import {
  getIAMClient,
  toSnakeCase,
  toCamelCase,
} from "../../lib/grpcClient.ts";

const queryAuditableServices: AppBlock = {
  name: "Query Auditable Services",
  description: `Returns a list of services that allow you to opt into audit logs that are not generated by default. To learn more about audit logs, see the [Logging documentation](https://cloud.google.com/logging/docs/audit).`,
  category: "IAM",
  inputs: {
    default: {
      config: {
        fullResourceName: {
          name: "Full Resource Name",
          description:
            "Required. The full resource name to query from the list of auditable services.  The name follows the Google Cloud Platform resource format. For example, a Cloud Platform project with id `my-project` will be named `//cloudresourcemanager.googleapis.com/projects/my-project`.",
          type: {
            type: "string",
            description:
              "Required. The full resource name to query from the list of auditable services.  The name follows the Google Cloud Platform resource format. For example, a Cloud Platform project with id `my-project` will be named `//cloudresourcemanager.googleapis.com/projects/my-project`.",
          },
          required: false,
        },
      },
      onEvent: async (input) => {
        const client = await getIAMClient(input.app.config);

        const request: Record<string, any> = {};
        if (input.event.inputConfig.fullResourceName !== undefined)
          request.fullResourceName = input.event.inputConfig.fullResourceName;

        const protoRequest = toSnakeCase(request);
        const result = await new Promise<any>((resolve, reject) => {
          client.queryAuditableServices(
            protoRequest,
            (err: any, response: any) => {
              if (err)
                reject(
                  new Error(
                    `gRPC error [${err.code}]: ${err.details || err.message}`,
                  ),
                );
              else resolve(response);
            },
          );
        });

        await events.emit(result ? toCamelCase(result) : {});
      },
    },
  },
  outputs: {
    default: {
      possiblePrimaryParents: ["default"],
      type: {
        type: "object",
        properties: {
          services: {
            type: "array",
            items: {
              type: "object",
              properties: {
                name: {
                  type: "string",
                  description:
                    "Public name of the service. For example, the service name for Cloud IAM is 'iam.googleapis.com'.",
                },
              },
              description: "Contains information about an auditable service.",
              additionalProperties: true,
            },
            description: "The auditable services for a resource.",
          },
        },
        description:
          "A response containing a list of auditable services for a resource.",
        additionalProperties: true,
      },
    },
  },
};

export default queryAuditableServices;
