import { AppBlock, events } from "@slflows/sdk/v1";
import { computeFetch } from "../../lib/restClient.ts";

const get: AppBlock = {
  name: "Instance Settings Service - Get",
  description: `Returns the specified Zone resource.`,
  category: "Instance Settings Service",
  inputs: {
    default: {
      config: {
        zone: {
          name: "Zone",
          description: "Name of the zone for this request.",
          type: {
            type: "string",
          },
          required: true,
        },
      },
      onEvent: async (input) => {
        const pathParams: Record<string, string> = {};
        pathParams.project = input.app.config.projectId as string;
        if (input.event.inputConfig.zone !== undefined)
          pathParams["zone"] = String(input.event.inputConfig.zone);

        const result = await computeFetch({
          config: input.app.config,
          method: "GET",
          pathTemplate:
            "/compute/v1/projects/{project}/zones/{zone}/instanceSettings",
          pathParams,
        });

        await events.emit(result || {});
      },
    },
  },
  outputs: {
    default: {
      possiblePrimaryParents: ["default"],
      type: {
        type: "object",
        properties: {
          fingerprint: {
            type: "string",
            description:
              "Specifies a fingerprint for instance settings, which is essentially a hash of the instance settings resource's contents and used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update the instance settings resource. You must always provide an up-to-date fingerprint hash in order to update or change the resource, otherwise the request will fail with error 412 conditionNotMet.  To see the latest fingerprint, make a get() request to retrieve the resource.",
          },
          kind: {
            type: "string",
            description:
              "Output only. [Output Only] Type of the resource. Alwayscompute#instance_settings for instance settings.",
          },
          metadata: {
            type: "object",
            properties: {
              items: {
                type: "object",
                additionalProperties: {
                  type: "string",
                },
                description:
                  "A metadata key/value items map. The total size of all keys and values must be less than 512KB.",
              },
              kind: {
                type: "string",
                description:
                  "Output only. [Output Only] Type of the resource. Always compute#metadata for metadata.",
              },
            },
            additionalProperties: true,
            description:
              "The metadata key/value pairs assigned to all the instances in the corresponding scope.",
          },
          zone: {
            type: "string",
            description:
              "Output only. [Output Only] URL of the zone where the resource resides You must specify this field as part of the HTTP request URL. It is not settable as a field in the request body.",
          },
        },
        description:
          "Represents a Instance Settings resource. You can use instance settings to configure default settings for Compute Engine VM instances. For example, you can use it to configure default machine type of Compute Engine VM instances.",
        additionalProperties: true,
      },
    },
  },
};

export default get;
